#!/usr/bin/env python3
"""Regenerate SymbolNames.kira and SymbolAssets.kira from cupertino_icons.

    pip install fonttools
    python3 kira-ui/tools/cupertino/generate.py

Two inputs, both fetched rather than vendored, because neither is ours:

  * `cupertino_icons` (pub.dev, MIT, Vladimir Kharlampidi / Framework7) ships
    `assets/CupertinoIcons.ttf` — the drawings, and nothing that names them.
  * Flutter's `packages/flutter/lib/src/cupertino/icons.dart` names them, and
    is the only place the name-to-codepoint map exists.

WHY THE SHARED EM BOX MATTERS. Every glyph is emitted with the SAME viewBox --
the font's em -- rather than one trimmed to its own bounds. A symbol is
rasterized TRIMMED TO ITS INK and fitted to whatever box the caller gives it, so
per-glyph viewBoxes make every icon come out the same ink height whatever it was
drawn at: `play_rectangle` is squat and `photo_on_rectangle` tall, and the
reference renders them at 69 and 83 device pixels for that reason. Trimmed
viewBoxes rendered both at 52 and the squat one towered over the type beside it.
The shared box keeps the proportions recoverable: `foundationIconInkTop`/
`Bottom` then report where a glyph's ink sits inside the em, and a caller sizing
by the em gets the set as it was drawn.
"""
import io, json, re, sys, tarfile, urllib.request
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.misc.transform import Transform

PKG = "https://pub.dev/api/archives/cupertino_icons-1.0.9.tar.gz"
DART = ("https://raw.githubusercontent.com/flutter/flutter/master/"
        "packages/flutter/lib/src/cupertino/icons.dart")
OUT = "kira-ui/app/"

def camel(name):
    return "".join(p.capitalize() if not p.isdigit() else p for p in name.split("_"))

def main():
    blob = urllib.request.urlopen(PKG, timeout=60).read()
    with tarfile.open(fileobj=io.BytesIO(blob)) as tar:
        ttf = tar.extractfile("assets/CupertinoIcons.ttf").read()
    dart = urllib.request.urlopen(DART, timeout=60).read().decode()

    # Both the one-line and the multiline `IconData(` spellings appear.
    pat = re.compile(r"static const IconData ([a-z0-9_]+) = IconData\(\s*0x([0-9a-fA-F]+)")
    names = {n: int(cp, 16) for n, cp in pat.findall(dart)}

    font = TTFont(io.BytesIO(ttf))
    glyphs, cmap = font.getGlyphSet(), font.getBestCmap()
    upem = font["head"].unitsPerEm
    asc, desc = font["hhea"].ascent, font["hhea"].descent   # descent is negative

    svgs = {}
    for name, cp in names.items():
        gname = cmap.get(cp)
        if gname is None:
            continue
        pen = SVGPathPen(glyphs)
        # A font's Y runs up and SVG's runs down; flip about the em's top.
        glyphs[gname].draw(TransformPen(pen, Transform(1, 0, 0, -1, 0, asc)))
        d = pen.getCommands()
        if d:
            svgs[name] = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %g %g" '
                          'fill="currentColor"><path d="%s"/></svg>' % (upem, asc - desc, d))

    ordered = sorted(svgs)
    with open(OUT + "SymbolNames.kira", "w") as f:
        f.write(HEADER_NAMES)
        for n in ordered:
            f.write("    %s\n" % camel(n))
        f.write("}\n")
    with open(OUT + "SymbolAssets.kira", "w") as f:
        f.write(HEADER_ASSETS)
        for n in ordered:
            f.write('        %s -> return "%s";\n'
                    % (camel(n), svgs[n].replace("\\", "\\\\").replace('"', '\\"')))
        f.write("    }\n}\n")
    print("wrote %d icons" % len(ordered))

HEADER_NAMES = '''import Foundation

// The Cupertino icon set's names. Generated by tools/cupertino/generate.py from
// cupertino_icons (MIT) with Flutter's own name-to-codepoint map. Do not edit.
//
// The names are Apple's: `doc_on_doc`, `play_rectangle`, `plus_square_on_square`
// arrive as `DocOnDoc`, `PlayRectangle`, `PlusSquareOnSquare`. That is the point
// of this set over a generic one -- a menu copying an iOS menu can ask for the
// glyph by the name Apple gives it instead of settling for the nearest shape.

enum Symbol {
    None
'''

HEADER_ASSETS = '''import Foundation

// Generated by tools/cupertino/generate.py from cupertino_icons (MIT). Do not
// edit.
//
// Every glyph carries the SAME viewBox -- the font's em box -- and that is
// load-bearing rather than incidental. See the generator's docstring.

function symbolAsset(symbol: borrow Symbol) -> String {
    match symbol {
        None -> return "";
'''

if __name__ == "__main__":
    sys.exit(main())
