[package]
name = "KiraUI"
version = "0.1.0"
kind = "library"
kira = "0.1.0"
module_root = "KiraUI"

[defaults]
execution_mode = "vm"
build_target = "host"

[dependencies]
KiraUIFoundation = { path = "../ui-foundation" }
